### PR TITLE
Add OAuth Token Authorization

### PR DESCRIPTION
**Pull request by Semidio**
Add OAuth Token Authorization to support 2-factor protected account.

### CODE REVIEW

**Comment by ceremcem** [comment]
Thanks for the PR. I've enabled the two-factor authentication for my account to test the code. However, I'm not able to create a gist with 

```
$ lsusb | create-gist.sh 266978
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   692  100    93  100   599    148    956 --:--:-- --:--:-- --:--:--  1105
----- ERROR -----
{
  "message": "Bad credentials",
  "documentation_url": "https://developer.github.com/v3"
}
-----------------

```

(where 266978 is my token). Would you provide an example usage?

**Comment by Semidio** [comment]
There are should use the GitHub Personal access tokens with atleast gist permission enabled, which you could create one at https://github.com/settings/tokens

**Comment by Semidio** [comment]
You should use GitHub Personal access tokens with atleast Gist permission enabled, which you could generate it at https://github.com/settings/tokens

**Comment by ceremcem** [comment]
So the procedure is: 

1. Go to https://github.com/settings/tokens/new and generate a new token with `create gist` permission.
2. Use the token for authentication: 

```
lsusb | create-gist.sh your-token-here
```

This nicely works. However, the changes break the current (simple) authentication style.

Would you mind adding this feature with `--token` switch or by reading from a configuration file maybe?

**Pull request merged**
